
full_scrape: True
ignore_previously_scraped: True
scrape_folder: 'scrapes'
log_folder: 'logs'


base_url: 'https://arbeidsplassen.nav.no'
buffer_size: 50

time_sleep_lower: 0.75
time_sleep_upper: 1.5